### ISSUE TITLE
Can't find WSL network 

### ISSUE THREAD

**Issue by jsturtevant** [Siemens-Healthineers/K2s#359] opened 2024-04-18 18:09 UTC
**Describe the bug**

I ran the basic install with the `--wsl` option but it failed to find the wsl network which is present. There were a few other errors in the output as well.

**To Reproduce**
```
.\k2s.exe install --wsl
🤖 Installing K2s 'k2s' v1.0.0+4f83aa8 in 'C:\Users\jstur\K2s-1.0.0' on Microsoft Windows 11 Enterprise 10.0.22631.3447 Build 22631.3447 using PowerShell 5
⏳ Write-Log : [10:21:06] wsl : WSL is finishing an upgrade...  At
⏳ C:\Users\jstur\K2s-1.0.0\smallsetup\common\GlobalFunctions.ps1:1284 char:5  +     wsl --version  +     ~~~~~~~~~~~~~
⏳    + CategoryInfo          : NotSpecified: (WSL is f...rade...:String) [], RemoteException      +
⏳ FullyQualifiedErrorId : NativeCommandError
⏳ At C:\Users\jstur\K2s-1.0.0\lib\scripts\k2s\base\Invoke-ExecScript.ps1:44 char:9
⏳ +         Write-Log $($_ | Out-String) -Error
⏳ +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
⏳     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
⏳     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log
⏳
⏳ [10:21:07] Setting up Windows worker node
⏳ [10:25:02] Setting up KubeMaster Distro
⏳ No vEthernet (WSL) found!
⏳ At C:\Users\jstur\K2s-1.0.0\smallsetup\common\GlobalFunctions.ps1:1330 char:9
⏳ +         throw "No vEthernet ($wslSwitch) found!"
⏳ +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
⏳     + CategoryInfo          : OperationStopped: (No vEthernet (WSL) found!:String) [], RuntimeException
⏳     + FullyQualifiedErrorId : No vEthernet (WSL) found!
⏳
E0418 10:40:22.210343   22612 psexecutor.go:445] Write-Log : [10:21:06] wsl : WSL is finishing an upgrade...  At
C:\Users\jstur\K2s-1.0.0\smallsetup\common\GlobalFunctions.ps1:1284 char:5  +     wsl --version  +     ~~~~~~~~~~~~~
   + CategoryInfo          : NotSpecified: (WSL is f...rade...:String) [], RemoteException      +
FullyQualifiedErrorId : NativeCommandError
At C:\Users\jstur\K2s-1.0.0\lib\scripts\k2s\base\Invoke-ExecScript.ps1:44 char:9
+         Write-Log $($_ | Out-String) -Error
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

No vEthernet (WSL) found!
At C:\Users\jstur\K2s-1.0.0\smallsetup\common\GlobalFunctions.ps1:1330 char:9
+         throw "No vEthernet ($wslSwitch) found!"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No vEthernet (WSL) found!:String) [], RuntimeException
    + FullyQualifiedErrorId : No vEthernet (WSL) found!
```

**Expected behavior**
It to find the WSL network that is already setup:

```
❯ get-hnsnetwork | Format-table -Property name

Name
----
WSL (Hyper-V firewall)
Default Switch
```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by C-U-Next-Tuesday** [comment] 2024-04-18 23:12
Lot of assumptions without any logs from wsl.
This can help with context - [collect_wsl_logs.ps1](https://gist.githubusercontent.com/Calvindd2f/3216535b0797960f191fcb9d1a7a368e/raw/a8ae4c701297c25b8a90db6d24557dce7540066b/collect_wsl_logs.ps1)

With that in mind, did you change the network adapter name?
  
The `GlobalFunctions.ps1` statically checks for the name `vEthernet (WSL)` - so if it has been changed it will not work. It is a static requirement and it will not work until the adapter name is `vEthernet (WSL)`.

```powershell
function Set-WSLSwitch() {
    $wslSwitch = 'WSL'
    Write-Log "Configuring internal switch $wslSwitch"

    $iteration = 60
    while ($iteration -gt 0) {
        $iteration--
        $ipindex = Get-NetAdapter -Name "vEthernet ($wslSwitch)" -ErrorAction SilentlyContinue | select -expand 'ifIndex'
        $oldIp = $null
        if ($ipindex) {
            $oldIp = (Get-NetIPAddress -InterfaceIndex $ipindex).IPAddress
        }
        if ($ipindex -and $oldIp) {
            Write-Log "ifindex of vEthernet ($wslSwitch): $ipindex"
            Write-Log "Old ip: $oldIp"
            if ($oldIp) {
                foreach ($ip in $oldIp) {
                    Remove-NetIPAddress -InterfaceIndex $ipindex -IPAddress $oldIp -Confirm:$False -ErrorAction SilentlyContinue
                }
            }

            break
        }

        Write-Log "No vEthernet ($wslSwitch) detected yet!"
        Start-Sleep 2
    }

    if ($iteration -eq 0) {
        throw "No vEthernet ($wslSwitch) found!"
    }

    New-NetIPAddress -IPAddress $global:IP_NextHop -PrefixLength 24 -InterfaceAlias "vEthernet ($wslSwitch)"
    # enable forwarding
    netsh int ipv4 set int "vEthernet ($wslSwitch)" forwarding=enabled | Out-Null
    # change index in order to have the Ethernet card as first card (also for much better DNS queries)
    $ipindex1 = Get-NetIPInterface | ? InterfaceAlias -Like "*$wslSwitch*" | ? AddressFamily -Eq IPv4 | select -expand 'ifIndex'
    Write-Log "Index for interface $wslSwitch : ($ipindex1) -> metric 25"
    Set-NetIPInterface -InterfaceIndex $ipindex1 -InterfaceMetric 25
}
```
  
On the assumption that you did not have WSL setup before running the script. You likely did not restart after initial configuration / setup, which is required for the network adapter to be registered.
  
  
  
  
Also the `Set-WSL` function is iffy, it runs the shutdown but does not [wait the 8 second grace period](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#the-8-second-rule-for-configuration-changes) . I'd just install wsl yourself then reboot then try again. If that fails, so much for skydiving.

**Comment by jsturtevant** [comment] 2024-04-19 00:44
interesting, I have wsl previous installed. It's been installed for a long time... 

I don't seem to have the net adapter it is looking for.  

```
Get-NetAdapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Loopbackk2s               Microsoft KM-TEST Loopback Adapter           62 Up                 1.2 Gbps
Wi-Fi                     Intel(R) Wi-Fi 6 AX201 160MHz                25 Up               866.7 Mbps
Local Area Connection     Xbox Wireless Adapter for Windows            16 Up                600 Mbps
Ethernet                  Surface Ethernet Adapter                     14 Disconnected          0 bps
Bluetooth Network Conn... Bluetooth Device (Personal
```

I'll try collecting the logs requested later

**Comment by jsturtevant** [comment] 2024-04-19 00:47
> On the assumption that you did not have WSL setup before running the script. You likely did not restart after initial configuration / setup, which is required for the network adapter to be registered.

oh , It seems that this tool created a separate wsl instance `KubeMaster` (and set it to the default, which is maybe a seperate issue). Where can I specify the wsl instance I want to use?  


```
 wsl -l
Windows Subsystem for Linux Distributions:
KubeMaster (Default)
Ubuntu-20.04
Ubuntu
```

I will try a restart with the new instance

**Comment by mahenarayan** [comment] 2024-04-19 05:55
@jsturtevant Thanks for trying out k2s and reporting the issue, currently k2s creates only an own wsl instance (kubemaster) and there is no support to use an existing wsl instance as of today and no plans either. 

Try the new instance installation again, if there are issues during installation, you can share the k2s.log file under C:\var\log.

@achimkist We need to document that there is no support for using an existing wsl instance with k2s.

**Comment by jsturtevant** [comment] 2024-04-19 15:58
I restarted and there was still no ethernet swith called WSL. I tried rerunning and not have any luck:

```
.\k2s.exe install --wsl
🤖 Installing K2s 'k2s' v1.0.0+4f83aa8 in 'C:\Users\jstur\K2s-1.0.0' on Microsoft Windows 11 Enterprise 10.0.22631.3447 Build 22631.3447 using PowerShell 5
⏳ [08:52:28] Setting up Windows worker node
⏳ [08:53:16] Setting up KubeMaster Distro
⏳ No vEthernet (WSL) found!
⏳ At C:\Users\jstur\K2s-1.0.0\smallsetup\common\GlobalFunctions.ps1:1330 char:9
⏳ +         throw "No vEthernet ($wslSwitch) found!"
⏳ +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
⏳     + CategoryInfo          : OperationStopped: (No vEthernet (WSL) found!:String) [], RuntimeException
⏳     + FullyQualifiedErrorId : No vEthernet (WSL) found!
⏳
E0419 08:56:12.762105   19828 psexecutor.go:445] No vEthernet (WSL) found!
At C:\Users\jstur\K2s-1.0.0\smallsetup\common\GlobalFunctions.ps1:1330 char:9
+         throw "No vEthernet ($wslSwitch) found!"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No vEthernet (WSL) found!:String) [], RuntimeException
    + FullyQualifiedErrorId : No vEthernet (WSL) found!

  ERROR   command execution failed, see log output above. Error: exit code 1
F0419 08:56:12.764255   19828 logging.go:42] command execution failed, see log output above. Error: exit code 1
```

Did I miss a step? Where/when is the switch created?

**Comment by jsturtevant** [comment] 2024-04-19 16:03
k2 logs: 
[k2s.log](https://github.com/Siemens-Healthineers/K2s/files/15042860/k2s.log)

**Comment by mahenarayan** [comment] 2024-04-19 16:26
Looks like wsl switch is not found with command `Get-NetAdapter` https://github.com/Siemens-Healthineers/K2s/blob/ccaf7afaacb8954c0b9fe94fbe4fa06b3d07d91e/smallsetup/common/GlobalFunctions.ps1#L1308 

Can you provide the output of PS commands `Get-NetAdapter` and `Get-NetIPInterface`?

We normally test k2s WSL installation against Windows 10, from the logs I can see that Windows 11 23H2 is used. It could be that there are changes related to wsl networking from Windows 10 23H2 to Windows 11 23H2. Hence the expected network switch is not found.  

Let me also try the installation on a Win 11 machine.

**Comment by mahenarayan** [comment] 2024-04-19 17:15
Thanks for sharing the output. Looks like the default switch name created for wsl is changed from `vEthernet (WSL)` to 
`vEthernet (WSL (Hyper-V firewall))` in the newer Windows 11.

I can also reproduce the same on Windows 11 23H2, our test suite for wsl is limited to Windows 10. We will need to provide a fix for this.

As a workaround, change the `$wslSwitch` value to `WSL (Hyper-V firewall)` in your local workspace to complete the installation. https://github.com/Siemens-Healthineers/K2s/blob/ccaf7afaacb8954c0b9fe94fbe4fa06b3d07d91e/smallsetup/common/GlobalFunctions.ps1#L1302

**Comment by mahenarayan** [comment] 2024-04-19 17:25
Another aspect is that the default wsl switch is no longer found with `Get-NetAdapter`. So, the script needs further changes for the workaround to work.
Replace `Get-NetAdapter` with `Get-NetIPInterface` to look for the switch name.
https://github.com/Siemens-Healthineers/K2s/blob/ccaf7afaacb8954c0b9fe94fbe4fa06b3d07d91e/smallsetup/common/GlobalFunctions.ps1#L1308

**Comment by mahenarayan** [comment] 2024-04-19 17:27
> That didn't work since there isn't a "switch" created just the network interface:
> 
> ```
>  No vEthernet (WSL (Hyper-V firewall)) found!
> ⏳ At C:\Users\jstur\K2s-1.0.0\smallsetup\common\GlobalFunctions.ps1:1330 char:9
> ⏳ +         throw "No vEthernet ($wslSwitch) found!"
> ```

Okay, I will try this out tomorrow.

**Comment by jsturtevant** [comment] 2024-04-19 17:28
> Replace `Get-NetAdapter` with `Get-NetIPInterface` to look for the switch name.

I didn't try this but will report back

**Comment by C-U-Next-Tuesday** [comment] 2024-04-19 18:43
> > Replace `Get-NetAdapter` with `Get-NetIPInterface` to look for the switch name.
> 
> I didn't try this but will report back

Renaming whatever your current WSL switch is to literally `vEthernet (WSL)` is the fix because of how the functions were created. The function makes assumptions people never bother edit the name.

The functions too specific to the specific adapter name "vEthernet (WSL)". It needs to be more flexible.

This is not a very flexible solution, the function should be redone.

-----------------------------------------

+ Instead of checkin specific adapter name; get all &  filter them.

```powershell
function Set-WSLSwitch {
    $adapters = Get-NetAdapter -ErrorAction SilentlyContinue -IncludeHidden
    $wslAdapter = $adapters | Where-Object {$_.InterfaceDescription -match "Hyper-V Virtual Ethernet*"}
    if ($wslAdapter) {
        $wslSwitch = $wslAdapter.Name
        #...
    } else {
        Write-Log "No WSL adapter found!"
    }
}
```  
  
or   

+ Use a parameter instead of hardcoding the adapter name, pass it as a parameter to the function.
  
or  

+ Use a regex pattern: Instead of checking for a static string, use regex to match `WSL` and `Ethernet`. 


-------------------------------------
```powershell
$wslAdapter |fl Name,InterfaceDescription

Name                 : vEthernet (Default Switch)
InterfaceDescription : Hyper-V Virtual Ethernet Adapter

Name                 : vEthernet (WSL (Hyper-V firewall))
InterfaceDescription : Hyper-V Virtual Ethernet Adapter #2
```

You can guess which one you need to rename `vEthernet (WSL)`

**Comment by jsturtevant** [comment] 2024-04-19 21:20
Adding `-IncludeHidden` hidden worked!  

```
ks
K2s SYSTEM STATUS
Setup: 'k2s', Version: 'v1.0.0'
 SUCCESS  The system is running

K8s server version: 'v1.25.13'
K8s client version: 'v1.25.13'
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| STATUS | NAME       | ROLE          | AGE  | VERSION  | INTERNAL-IP  | OS-IMAGE                       | KERNEL-VERSION                     | CONTAINER-RUNTIME  |
| Ready  | james-ms   | worker        | 5m4s | v1.25.13 | 172.20.1.2   | Windows 10 Enterprise          | 10.0.22631.3447                    | containerd://1.7.9 |
| Ready  | kubemaster | control-plane | 1d3h | v1.25.13 | 172.19.1.100 | Debian GNU/Linux 11 (bullseye) | 5.15.146.1-microsoft-standard-WSL2 | cri-o://1.25.2     |
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
 SUCCESS  All nodes are ready
```

agree with @C-U-Next-Tuesday that it should be more dynamic.  Note `  $wslAdapter = $adapters | Where-Object {$_.InterfaceDescription -match "Hyper-V Virtual Ethernet*"}` returned two different adapters on my system so that would need to be refined.

There are some other changes that need to be included as the firewall rules didn't apply properly (probably becuase needs something like `-includehidden` as well on those commands):

```
 Write-Log : [14:05:27] New-NetFirewallRule : The specified interface was not found on the system.    At
⏳ C:\Users\jstur\K2s-1.0.0\smallsetup\StartK8s.ps1:476 char:13  +             New-NetFirewallRule -DisplayName 'WSL Inbound' -Group "k2 ...  +
⏳ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      + CategoryInfo          : InvalidArgument:
⏳ (MSFT_NetFirewallRule:root/standardcimv2/MSFT_NetFirewallRule) [New-NetFirewallRule], CimException      + FullyQualifiedErrorId : HRESULT
⏳ 0x80070057,New-NetFirewallRule
⏳ At C:\Users\jstur\K2s-1.0.0\lib\scripts\k2s\base\Invoke-ExecScript.ps1:44 char:9
⏳ +         Write-Log $($_ | Out-String) -Error
⏳ +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
⏳     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
⏳     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log
⏳
⏳ Write-Log : [14:05:27] New-NetFirewallRule : The specified interface was not found on the system.    At
⏳ C:\Users\jstur\K2s-1.0.0\smallsetup\StartK8s.ps1:477 char:13  +             New-NetFirewallRule -DisplayName 'WSL Outbound'-Group "k2 ...  +
⏳ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      + CategoryInfo          : InvalidArgument:
⏳ (MSFT_NetFirewallRule:root/standardcimv2/MSFT_NetFirewallRule) [New-NetFirewallRule], CimException      + FullyQualifiedErrorId : HRESULT
⏳ 0x80070057,New-NetFirewallRule
⏳ At C:\Users\jstur\K2s-1.0.0\lib\scripts\k2s\base\Invoke-ExecScript.ps1:44 char:9
⏳ +         Write-Log $($_ | Out-String) -Error
⏳ +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
⏳     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
⏳     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log
```

**Comment by jsturtevant** [comment] 2024-04-19 21:25
The change I made was:

```
function Set-WSLSwitch() {
    $wslSwitch = 'WSL (Hyper-V firewall)'
    Write-Log "Configuring internal switch $wslSwitch"

    $iteration = 60
    while ($iteration -gt 0) {
        $iteration--
        $ipindex = Get-NetAdapter -Name "vEthernet ($wslSwitch)" -ErrorAction SilentlyContinue -IncludeHidden | select -expand 'ifIndex'
        $oldIp = $null
        if ($ipindex) {
            $oldIp = (Get-NetIPAddress -InterfaceIndex $ipindex).IPAddress
        }
....
```

**Comment by krotz-dieter** [comment] 2024-04-22 07:04
Many thanks to [jsturtevant](https://github.com/jsturtevant), [C-U-Next-Tuesday](https://github.com/C-U-Next-Tuesday) for the analysis and findings, we will takeover the changes.

**Closed** 2024-04-23 07:10 UTC
