### ISSUE TITLE
Redundant kubectl executable needs to be removed from k2s bin. 

### ISSUE THREAD

**Issue by abhitoshj** [Siemens-Healthineers/K2s#54] opened 2024-01-25 13:32 UTC
kubectl executable can be found in bin and bin/exe folders in k2s. One of them needs to be removed

**Comment by jgriegershs** [comment] 2024-01-25 13:34
@abhitoshj Isn't this a duplicate of #2 ?

**Comment by abhitoshj** [comment] 2024-01-25 13:36
yes seems to be the case.

**Closed** 2024-01-29 15:52 UTC
Labels: duplicate
